### ISSUE TITLE
Next scheduled release

### ISSUE THREAD

**Issue by maarten-betman** [ritchie46/pygef#62]
@martinapippi Is the Pygef team planning to release a new version to PyPI following the recent PR's?

**Comment by martinapippi** [comment]
No, we don't have a plan for the next release yet. @ritchie46 what do you think about it? Maybe we can solve issues #61 and #58 first.

**Comment by ritchie46** [comment]
Don't really have a clear view on the state of the changes? Are there API/ feature changes in latest PRs? Or are they just patches.

> we can solve issues #61 and #57 first.
How much work is needed for them?

**Comment by martinapippi** [comment]
They are mostly patches. #59 added an attribute to `ParseCPT`.

#57 should be almost done (it needs a unit test)
#61 depends on the strategy that we choose. If we choose to change the name it will take some time but no more than a work day. We will however not have backwards compatibility since we will change the name of methods's parameters and columns of `pd.DataFrame`s, so then it might be good to update to 0.5.0.

**Comment by maarten-betman** [comment]
@martinapippi any update?

**Comment by martinapippi** [comment]
@maarten-betman pygef has been updated to the last version in PyPi
